.PHONY: start-server-a
start-server-a:
	python3 server.py 9091 "Hello AAA!"

.PHONY: start-server-b
start-server-b:
	python3 server.py 9092 "Hello BBB!"

.PHONY: start-envoy-proxy
start-envoy-proxy:
	envoy --config-path ./config.yml







